Fuente
https://www.indec.gob.ar/indec/web/Institucional-Indec-BasesDeDatos

Variables
Ocupacion
Region
Sector
Salario

##0.PreConfiguración

In [ ]:
import pandas as pd
pd.__version__

'1.1.5'

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')
!ls

Mounted at /content/drive/
drive  sample_data

In [ ]:
%cd'/content/drive/Shareddrives/BID/Ciudades/MicroDatos/Argentina'
!ls

/content/drive/Shareddrives/BID/Ciudades/MicroDatos/Argentina
 ArgBD2T2017_2021				    EPH_usu_3_Trim_2018_xls.zip
'ARGENTINA MICRODATO EPH_usu_1_Trim_2021_xls.zip'   EPH_usu_3_Trim_2019_xls.zip
 EPH_usu_1er_Trim_2017_xls.zip			    EPH_usu_3_Trim_2020_xls.zip
 EPH_usu_1_Trim_2018_xls.zip			    EPH_usu_4_Trim_2017_xls.zip
 EPH_usu_1_Trim_2019_xls.zip			    EPH_usu_4_Trim_2018_xls.zip
 EPH_usu_1_Trim_2020_xls.zip			    EPH_usu_4_Trim_2019_xls.zip
 EPH_usu_2_Trim_2017_xls.zip			    EPH_usu_4_Trim_2020_xls.zip
 EPH_usu_2_Trim_2018_xls.zip			    usu_individual_t217.xls
 EPH_usu_2_Trim_2019_xls.zip			    usu_individual_t218.xls
 EPH_usu_2_Trim_2020_xls.zip			    USU_individual_t219.xls
 EPH_usu_2_Trim_2021_xls.zip			    usu_Individual_T220.xlsx
 EPH_usu_3_Trim_2017_xls.zip			    usu_individual_T221.xlsx

##1.Parámetros Metodológicos Argentinos

https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_registro_t217.pdf
AGLOMERADO N(2) Código de Aglomerado
 02 = Gran La Plata
 03 = Bahía Blanca - Cerri
 04 = Gran Rosario
 05 = Gran Santa Fé
 06 = Gran Paraná
 07 = Posadas
 08 = Gran Resistencia
 09 = Cdro. Rivadavia - R.Tilly
 10 = Gran Mendoza
 12 = Corrientes
 13 = Gran Córdoba
 14 = Concordia
 15 = Formosa
 17 = Neuquén – Plottier
 18 = S.del Estero - La Banda
 19 = Jujuy - Palpalá
 20 = Río Gallegos
 22 = Gran Catamarca
 23 = Salta
 25 = La Rioja
 26 = San Luis - El Chorrillo
 27 = Gran San Juan
 29 = Gran Tucumán - T. Viejo
 30 = Santa Rosa - Toay
 31 = Ushuaia - Río Grande
 32 = Ciudad de Bs As
 33 = Partidos del GBA
 34 = Mar del Plata - Batán
 36 = Río Cuarto
 38 = San Nicolás – Villa Constitución
 91 = Rawson – Trelew
 93 = Viedma – Carmen de Patagones

ESTADO N(1) CONDICIÓN DE ACTIVIDAD
 0 = Entrevista individual no realizada ( no
 respuesta al Cuestionario Individual)
 1 = Ocupado
 2 = Desocupado
 3 = Inactivo
 4 = Menor de 10 años

PP04B_COD N(5) ¿A qué se dedica o produce el negocio/ empresa/
 institución?
 (Ver Clasificador de Actividades Económicas para
 Encuestas Sociodemográficas del Mercosur – CAES-
 MERCOSUR)

p47T N (10) MONTO DE INGRESO TOTAL INDIVIDUAL

Factores de expansión
Para minimizar el efecto de la no respuesta de ingresos, se asignó a los no respondentes el
comportamiento de los respondentes por estrato de la muestra, por lo cual, para el tratamiento de los
ingresos y la pobreza se presentan dos tipos de ponderadores:
1. El campo PONDERA, sin corrección, que se utiliza además para el resto de las variables.
2. Los campos PONDII, PONDIIO, PONDIH con corrección por no respuesta:
• PONDII para el tratamiento del ingreso total individual(p47t, decindr, adecindr, rdecindr, pdecindr,
gdecindr, idecindr).
• PONDIIO para el ingreso de la ocupación principal (p21, pp06c, pp06d, pp08d1, pp08d4, pp08f1,
pp08f2, pp08j1, pp08j2,pp08j3, decocur, adecocur, rdecocur, pdecocur, gdecocur, idecocur).
• PONDIH para el ingreso total familiar (ITF, decifr, adecifr, rdecifr, pdecifr, gdecifr, idecifr), el ingreso per
cápita familiar (IPCF, deccfr, adecifr, rdecifr, pdecifr, gdecifr, idecifr).

##1. Cargando Bases 2T desde 2017 hasta 2021

2T2017

In [ ]:
path = '/content/drive/Shareddrives/BID/Ciudades/MicroDatos/Argentina/usu_individual_t217.xls'
df2t17 = pd.read_excel(path)

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

In [ ]:
df2t17.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59755 entries, 0 to 59754
Columns: 177 entries, CODUSU to PONDIH
dtypes: datetime64[ns](1), float64(93), int64(61), object(22)
memory usage: 80.7+ MB

In [ ]:
df2t17.head(5)

                          CODUSU  ANO4  TRIMESTRE  ...  PDECCFR  ADECCFR  PONDIH
0  TQRMNORWQHMMLNCDEFIAH00507965  2017          2  ...                06    1207
1  TQRMNORWQHMMLNCDEFIAH00507965  2017          2  ...                06    1207
2  TQRMNORWQHMMLNCDEFIAH00507965  2017          2  ...                06    1207
3  TQSMNORWQHMMLNCDEFIAH00507893  2017          2  ...                03     783
4  TQSMNORWQHMMLNCDEFIAH00507893  2017          2  ...                03     783

[5 rows x 177 columns]

In [ ]:
df2t17.tail(5)

                              CODUSU  ANO4  TRIMESTRE  ...  PDECCFR  ADECCFR  PONDIH
59750  TQRMNOSTTHJKKPCDEIOAH00486599  2017          2  ...       10       10     237
59751  TQRMNOSTTHJKKPCDEIOAH00486599  2017          2  ...       10       10     237
59752  TQRMNOSPRHJMKOCDEIOAH00486636  2017          2  ...                         0
59753  TQRMNOQWSHJNKSCDEIOAH00486690  2017          2  ...       01       01     155
59754  TQRMNOQWSHJNKSCDEIOAH00486690  2017          2  ...       01       01     155

[5 rows x 177 columns]

In [ ]:
df2t17['AGLOMERADO'].value_counts()

33    8900
23    2751
29    2570
13    2528
32    2354
10    2259
4     2118
27    1928
22    1899
18    1754
5     1740
19    1712
25    1677
26    1627
6     1588
38    1533
12    1509
7     1484
36    1447
14    1429
15    1425
2     1420
3     1352
91    1338
31    1307
93    1300
9     1295
8     1234
17    1177
34    1129
30    1022
20     949
Name: AGLOMERADO, dtype: int64

In [ ]:
df2t17['PP04B_COD'].value_counts()

8401.0    2740
4000.0    2520
8501.0    1998
9700.0    1781
8600.0    1243
          ...
38.0         1
4801.0       1
9900.0       1
27.0         1
3900.0       1
Name: PP04B_COD, Length: 146, dtype: int64

In [ ]:
df2t17['ESTADO'].value_counts()

3    24771
1    24238
4     8812
2     1860
0       74
Name: ESTADO, dtype: int64

In [ ]:
df2t17['P47T'].value_counts()

 0.0        24398
-9.0         5267
 10000.0     1678
 6000.0      1578
 15000.0     1473
            ...
 5860.0         1
 4833.0         1
 9670.0         1
 3050.0         1
 6655.0         1
Name: P47T, Length: 944, dtype: int64

In [ ]:
df2t17renombrado = df2t17.rename(columns={"ESTADO": "ocupados", "PP04B_COD": "sector", "AGLOMERADO": "ciudad", "P47T": "salario", "PONDERA": "factor"})

In [ ]:
df2t17renombrado.head(3)

                          CODUSU  ANO4  TRIMESTRE  ...  PDECCFR  ADECCFR  PONDIH
0  TQRMNORWQHMMLNCDEFIAH00507965  2017          2  ...                06    1207
1  TQRMNORWQHMMLNCDEFIAH00507965  2017          2  ...                06    1207
2  TQRMNORWQHMMLNCDEFIAH00507965  2017          2  ...                06    1207

[3 rows x 177 columns]

In [ ]:
df2t17ARG = df2t17renombrado.loc[:,['ocupados', 'ciudad', 'sector', 'salario', 'factor']]

In [ ]:
df2t17ARG

       ocupados  ciudad  sector  salario  factor
0             3       2     NaN   5900.0     504
1             3       2     NaN   5900.0     504
2             1       2  4502.0  10000.0     504
3             3       2     NaN   1900.0     504
4             1       2  4000.0  14000.0     504
...         ...     ...     ...      ...     ...
59750         1      38  8600.0  31200.0     162
59751         3      38     NaN   6200.0     162
59752         3      38     NaN     -9.0     100
59753         1      38  1009.0   9000.0     109
59754         3      38     NaN      0.0     109

[59755 rows x 5 columns]

In [ ]:
Trim2de2017ARG = df2t17ARG.assign(Trimestre=2017)

In [ ]:
Trim2de2017ARG

       ocupados  ciudad  sector  salario  factor  Trimestre
0             3       2     NaN   5900.0     504       2017
1             3       2     NaN   5900.0     504       2017
2             1       2  4502.0  10000.0     504       2017
3             3       2     NaN   1900.0     504       2017
4             1       2  4000.0  14000.0     504       2017
...         ...     ...     ...      ...     ...        ...
59750         1      38  8600.0  31200.0     162       2017
59751         3      38     NaN   6200.0     162       2017
59752         3      38     NaN     -9.0     100       2017
59753         1      38  1009.0   9000.0     109       2017
59754         3      38     NaN      0.0     109       2017

[59755 rows x 6 columns]

2T2018

In [ ]:
path =  '/content/drive/Shareddrives/BID/Ciudades/MicroDatos/Argentina/usu_individual_t218.xls'
df2t18 = pd.read_excel(path)

WARNING *** file size (96425626) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

In [ ]:
df2t18

                              CODUSU  ANO4  TRIMESTRE  ...  PDECCFR  ADECCFR  PONDIH
0      TQRMNOQSWHMMMLCDEFIAH00507884  2018          2  ...                         0
1      TQRMNOQSWHMMMLCDEFIAH00507884  2018          2  ...                         0
2      TQRMNOTRPHMOLQCDEFIAH00588988  2018          2  ...                10     630
3      TQRMNOPWRHKNLPCDEFIAH00606240  2018          2  ...                01     944
4      TQRMNOPWRHKNLPCDEFIAH00606240  2018          2  ...                01     944
...                              ...   ...        ...  ...      ...      ...     ...
57830  TQRMNOSSXHKKKQCDEOJAH00611537  2018          2  ...                         0
57831  TQRMNOSSXHKKKQCDEOJAH00611537  2018          2  ...                         0
57832  TQRMNOSSXHKKKQCDEOJAH00611537  2018          2  ...                         0
57833  TQRMNOPSPHMOKOCDEOJAH00611677  2018          2  ...       08       08     105
57834  TQRMNOPSPHMOKOCDEOJAH00611677  2018          2  ...       08       08     105

[57835 rows x 177 columns]

In [ ]:
df2t18['AGLOMERADO'].value_counts()

33    8392
23    2721
29    2521
13    2471
32    2195
10    2163
4     2037
18    1798
22    1793
19    1755
25    1739
27    1731
5     1656
6     1625
26    1616
38    1491
15    1470
8     1417
36    1384
7     1379
93    1369
12    1355
91    1313
2     1306
3     1297
14    1292
34    1243
31    1176
9     1166
17    1093
30     965
20     906
Name: AGLOMERADO, dtype: int64

In [ ]:
df2t18['ESTADO'].value_counts()

1    23686
3    23555
4     8539
2     1982
0       73
Name: ESTADO, dtype: int64

In [ ]:
df2t18['PP04B_COD'].value_counts()

8401.0    2664
4000.0    2448
8501.0    1834
9700.0    1733
8600.0    1226
          ...
9900.0       1
35.0         1
4909.0       1
1.0          1
20.0         1
Name: PP04B_COD, Length: 144, dtype: int64

In [ ]:
df2t18['P47T'].value_counts()

 0.0         23059
-9.0          4609
 15000.0      1514
 20000.0      1423
 10000.0      1422
             ...
 8545.0          1
 118000.0        1
 3760.0          1
 34200.0         1
 1440.0          1
Name: P47T, Length: 970, dtype: int64

In [ ]:
df2t18renombrado = df2t18.rename(columns={"ESTADO": "ocupados", "PP04B_COD": "sector", "AGLOMERADO": "ciudad", "P47T": "salario", "PONDERA": "factor"})

In [ ]:
df2t18ARG = df2t18renombrado.loc[:,['ocupados', 'ciudad', 'sector', 'salario', 'factor']]

In [ ]:
Trim2de2018ARG = df2t18ARG.assign(Trimestre=2018)

In [ ]:
Trim2de2018ARG

       ocupados  ciudad  sector  salario  factor  Trimestre
0             1       2  7400.0     -9.0     619       2018
1             1       2  4807.0     -9.0     619       2018
2             3       2     NaN  37600.0     543       2018
3             2       2     NaN      0.0     451       2018
4             3       2     NaN      0.0     451       2018
...         ...     ...     ...      ...     ...        ...
57830         1      93  5601.0  15700.0     113       2018
57831         2      93     NaN    700.0     113       2018
57832         3      93     NaN      0.0     113       2018
57833         1      93  9700.0  14000.0      70       2018
57834         3      93     NaN   9500.0      70       2018

[57835 rows x 6 columns]

2T2019

In [ ]:
path = '/content/drive/Shareddrives/BID/Ciudades/MicroDatos/Argentina/USU_individual_t219.xls'
df2t19 = pd.read_excel(path)

In [ ]:
df2t19.describe

<bound method NDFrame.describe of                               CODUSU  ANO4  TRIMESTRE  ...  PDECCFR  ADECCFR  PONDIH
0      TQRMNOPTPHLKKSCDEFIAH00634909  2019          2  ...                         0
1      TQRMNOPTPHLKKSCDEFIAH00634909  2019          2  ...                         0
2      TQRMNOPTPHLKKSCDEFIAH00634909  2019          2  ...                         0
3      TQRMNOPTPHLKKSCDEFIAH00634909  2019          2  ...                         0
4      TQRMNOPYTHJLKRCDEFIAH00611682  2019          2  ...                         0
...                              ...   ...        ...  ...      ...      ...     ...
59253  TQRMNOQSPHKNLMCDEOJAH00640324  2019          2  ...       05       03     110
59254  TQRMNOSTPHKNLMCDEOJAH00611579  2019          2  ...       05       03     112
59255  TQRMNOSTPHKNLMCDEOJAH00611579  2019          2  ...       05       03     112
59256  TQRMNOQQPHLMLLCDEOJAH00640325  2019          2  ...       10       09      64
59257  TQRMNOQQPHLMLLCDEOJAH00640325  2019          2  ...       10       09      64

[59258 rows x 177 columns]>

In [ ]:
df2t19renombrado = df2t19.rename(columns={"ESTADO": "ocupados", "PP04B_COD": "sector", "AGLOMERADO": "ciudad", "P47T": "salario", "PONDERA": "factor"})

In [ ]:
df2t19ARG = df2t19renombrado.loc[:,['ocupados', 'ciudad', 'sector', 'salario', 'factor']]

In [ ]:
Trim2de2019ARG = df2t19ARG.assign(Trimestre=2019)

In [ ]:
Trim2de2019ARG

       ocupados  ciudad  sector  salario  factor  Trimestre
0             1       2  8401.0     -9.0     927       2019
1             1       2  8501.0     -9.0     927       2019
2             2       2     NaN      0.0     927       2019
3             3       2     NaN      0.0     927       2019
4             3       2     NaN   6000.0     827       2019
...         ...     ...     ...      ...     ...        ...
59253         3      93     NaN  15000.0     107       2019
59254         3      93     NaN  10000.0     107       2019
59255         3      93     NaN  10000.0     107       2019
59256         3      93     NaN  65000.0      60       2019
59257         4      93     NaN      0.0      60       2019

[59258 rows x 6 columns]

2T2020

In [ ]:
path = '/content/drive/Shareddrives/BID/Ciudades/MicroDatos/Argentina/usu_Individual_T220.xlsx'
df2t20 = pd.read_excel(path)
df2t20.describe

<bound method NDFrame.describe of                               CODUSU  ANO4  TRIMESTRE  ...  PDECCFR  ADECCFR  PONDIH
0      TQRMNORYPHJOKOCDEHMHF00658909  2020          2  ...      NaN        9     393
1      TQRMNORYPHJOKOCDEHMHF00658909  2020          2  ...      NaN        9     393
2      TQRMNOQPVHLOKOCDEHMHF00637896  2020          2  ...      NaN        6     140
3      TQRMNOQPVHLOKOCDEHMHF00637896  2020          2  ...      NaN        6     140
4      TQRMNOQPVHLOKOCDEHMHF00637896  2020          2  ...      NaN        6     140
...                              ...   ...        ...  ...      ...      ...     ...
37127  TQRMNOSTSHJNKSCDEOJAH00659460  2020          2  ...      NaN        4     230
37128  TQRMNOSTSHJNKSCDEOJAH00659460  2020          2  ...      NaN        4     230
37129  TQRMNOPPYHMMKNCDEOJAH00634645  2020          2  ...      NaN        6     112
37130  TQRMNOQSSHJMKPCDEOJAH00659461  2020          2  ...      NaN        9     178
37131  TQRMNOQSSHJMKPCDEOJAH00659461  2020          2  ...      NaN        9     178

[37132 rows x 177 columns]>

In [ ]:
df2t20renombrado = df2t20.rename(columns={"ESTADO": "ocupados", "PP04B_COD": "sector", "AGLOMERADO": "ciudad", "P47T": "salario", "PONDERA": "factor"})

In [ ]:
df2t20ARG = df2t20renombrado.loc[:,['ocupados', 'ciudad', 'sector', 'salario', 'factor']]

In [ ]:
Trim2de2020ARG = df2t20ARG.assign(Trimestre=2020)

In [ ]:
Trim2de2020ARG

       ocupados  ciudad  sector  salario  factor  Trimestre
0             3      26     NaN      0.0     316       2020
1             4      26     NaN      0.0     316       2020
2             1      26  6000.0  38000.0     120       2020
3             1      26  8501.0  40000.0     120       2020
4             3      26     NaN      0.0     120       2020
...         ...     ...     ...      ...     ...        ...
37127         3      93     NaN  15000.0     140       2020
37128         1      93  4000.0  14000.0     140       2020
37129         3      93     NaN  22000.0     104       2020
37130         1      93  8000.0  30000.0     117       2020
37131         1      93  8501.0  60000.0     117       2020

[37132 rows x 6 columns]

2T2021

In [ ]:
path = '/content/drive/Shareddrives/BID/Ciudades/MicroDatos/Argentina/usu_individual_T221.xlsx'
df2t21 = pd.read_excel(path)
df2t21.describe

<bound method NDFrame.describe of                               CODUSU  ANO4  TRIMESTRE  ...  PDECCFR  ADECCFR  PONDIH
0      TQRMNOQUVHKNLPCDEFIAH00652248  2021          2  ...      NaN       12       0
1      TQRMNOQUVHKNLPCDEFIAH00652248  2021          2  ...      NaN       12       0
2      TQRMNOQUVHKNLPCDEFIAH00652248  2021          2  ...      NaN       12       0
3      TQRMNOQUVHKNLPCDEFIAH00652248  2021          2  ...      NaN       12       0
4      TQRMNOQPUHJMLUCDEFIAH00707685  2021          2  ...      NaN       12       0
...                              ...   ...        ...  ...      ...      ...     ...
47080  TQRMNORQUHMMMSCDEIIAD00702443  2021          2  ...      NaN       10     884
47081  TQRMNORQUHMMMSCDEIIAD00702443  2021          2  ...      NaN       10     884
47082  TQRMNORQUHMMMSCDEIIAD00702443  2021          2  ...      NaN       10     884
47083  TQRMNORQUHMMMSCDEIIAD00702443  2021          2  ...      NaN       10     884
47084  TQRMNORQUHMMMSCDEIIAD00702443  2021          2  ...      NaN       10     884

[47085 rows x 177 columns]>

In [ ]:
df2t21renombrado = df2t21.rename(columns={"ESTADO": "ocupados", "PP04B_COD": "sector", "AGLOMERADO": "ciudad", "P47T": "salario", "PONDERA": "factor"})

In [ ]:
df2t21ARG = df2t21renombrado.loc[:,['ocupados', 'ciudad', 'sector', 'salario', 'factor']]

In [ ]:
Trim2de2021ARG = df2t21ARG.assign(Trimestre=2021)

In [ ]:
Trim2de2021ARG

       ocupados  ciudad  sector   salario  factor  Trimestre
0             3       2     NaN   18800.0     355       2021
1             1       2  5300.0      -9.0     355       2021
2             3       2     NaN       0.0     355       2021
3             4       2     NaN       0.0     355       2021
4             1       2  4803.0      -9.0     516       2021
...         ...     ...     ...       ...     ...        ...
47080         1      32  9999.0  732000.0     250       2021
47081         1      32  4804.0   55000.0     250       2021
47082         1      32  8200.0   50000.0     250       2021
47083         1      32  9999.0  360000.0     250       2021
47084         2      32     NaN       0.0     250       2021

[47085 rows x 6 columns]

##2.BASE UNIFICADA Y DEPURACIÓN

In [ ]:
BDARG2T = pd.concat([Trim2de2017ARG, Trim2de2018ARG, Trim2de2019ARG, Trim2de2020ARG, Trim2de2021ARG])

NameError: ignored

In [ ]:
BDARG2T

NameError: ignored

Depurando OCUPADOS

In [ ]:
BDARG2T['ocupados'].value_counts()

Limpiamos la variable ocupados con 1 para los ocupados y 0 para las demás opciones de 0, 2, 3 y 4

In [ ]:
#Creamos diccionario para ajuste de la variables ocupados
di = {0: 0, 1: 1, 2:0, 3:0, 4:0}

In [ ]:
BDARG2T_ocupacion = BDARG2T.replace({'ocupados':di})

In [ ]:
BDARG2T_ocupacion

Creamos la variable OCU que incluye el factor de expansión por cada ocupado

In [ ]:
OCU_1 = BDARG2T_ocupacion['ocupados']*BDARG2T_ocupacion['factor']

In [ ]:
OCU_1

Agregamos la nueva variable a la base de datos

In [ ]:
BDARG2T_ocupacion_1 = pd.concat([BDARG2T_ocupacion, OCU_1], axis=1)

In [ ]:
BDARG2T_ocupacion_1

Le ajustamos el nombre a la variable que aparece nombrada como 0 y la llamaremos OCU

In [ ]:
BDrenombradaOCU = BDARG2T_ocupacion_1.rename(columns={0:"OCU"})

In [ ]:
BDrenombradaOCU

Cambiamos los valores NaN por ceros

In [ ]:
BDsinNan = BDrenombradaOCU.fillna('0')

Dejamos la nueva variable OCU y retiramos las variables ocupados y factor

In [ ]:
BDArg_2017_2021 = BDsinNan.loc[:, ['ciudad', 'sector', 'salario', 'Trimestre', 'OCU']]

In [ ]:
BDArg_2017_2021

DEPURAMOS CIUDADES

Aglomerado 02 = Gran La Plata 03 = Bahía Blanca - Cerri 04 = Gran Rosario 05 = Gran Santa Fé 06 = Gran Paraná 07 = Posadas 08 = Gran Resistencia 09 = Cdro. Rivadavia - R.Tilly 10 = Gran Mendoza 12 = Corrientes 13 = Gran Córdoba 14 = Concordia 15 = Formosa 17 = Neuquén – Plottier 18 = S.del Estero - La Banda 19 = Jujuy - Palpalá 20 = Río Gallegos 22 = Gran Catamarca 23 = Salta 25 = La Rioja 26 = San Luis - El Chorrillo 27 = Gran San Juan 29 = Gran Tucumán - T. Viejo 30 = Santa Rosa - Toay 31 = Ushuaia - Río Grande 32 = Ciudad de Bs As 33 = Partidos del GBA 34 = Mar del Plata - Batán 36 = Río Cuarto 38 = San Nicolás – Villa Constitución 91 = Rawson – Trelew 93 = Viedma – Carmen de Patagones

In [ ]:
BD_Depur_Ocu_Ciudad = BDArg_2017_2021.replace(
    {'ciudad': {
        2: "LaPlata",
        3: "BahíaBlanca",
        4: "Rosario",
        5: "SantaFé",
        6: "Paraná",
        7: "Posadas",
        8: "Resistencia",
        9: "Rivadavia",
        10: "Mendoza",
        12: "Corrientes",
        13: "Córdoba",
        14: "Concordia",
        15: "Formosa",
        17: "Neuquén",
        18: "Estero",
        19: "Jujuy",
        20: "Gallegos",
        22: "Catamarca",
        23: "Salta",
        25: "Rioja",
        26: "SanLuis",
        27: "SanJuan",
        29: "Tucumán",
        30: "SantaRosa",
        31: "Ushuaia",
        32: "BsAs",
        33: "PartidosdelGBA",
        34: "MarDelPlata",
        36: "RíoCuarto",
        38: "SanNicolás",
        91: "Rawson",
        93: "Viedma"
    }       
    }
)

In [ ]:
df_limpio_ocu_ciudad_pais_trim1 = BD_Depur_Ocu_Ciudad.assign(country='Argentina')
df_limpio_ocu_ciudad_pais_trim2 = df_limpio_ocu_ciudad_pais_trim1.assign(quarter=2)
df_limpio_ocu_ciudad_pais_trim3 = df_limpio_ocu_ciudad_pais_trim2.rename(columns={'Trimestre':"year"})
df_limpio_ocu_ciudad_pais_trim4 = df_limpio_ocu_ciudad_pais_trim3.rename(columns={'OCU':"employs"})
df_limpio_ocu_ciudad_pais_trim5 = df_limpio_ocu_ciudad_pais_trim4.rename(columns={'ciudad':"city"})
df_limpio_ocu_ciudad_pais_trim6 = df_limpio_ocu_ciudad_pais_trim5.rename(columns={'salario':"salary"})
df_limpio_ocu_ciudad_pais_trim6

In [ ]:
df_pura = df_limpio_ocu_ciudad_pais_trim6[['year', 'quarter','country', 'city', 'employs', 'sector', 'salary']]
df_pura

In [ ]:
df_pura_ciiu = df_pura.rename(columns={'sector':"ciiu"})
df_pura_ciiu

DEPURAMOS SECTORES

Rev.4
agricultura (01,02,03), Minas (05,06,07,08,09), Industria (10, 11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33) Electricidad (35), AguaYSanea(36,37,38,39), Construcción (40), Comercio (45, 48), Transporte (49, 50, 51, 52, 53), AlojaYComidas (55,56), InformaciónYComunicación (58, 59, 60, 61, 62, 63), FinanzasYSeguros (64,65,66), Inmobiliarias (68), Profesionales,CientificasYtecnicas (69,70,71,72,73,74,75), Administrativas (77,78,79,80,81,82), AdminPública(83,84), Enseñanza(85), Salud(86,87,88) Artes (90,91,92,93), Otras (94,95,96), Hogar (97,98), Extraterritoriales (99)

Creamos función de clasificación entre rangos para los nombres de los sectores

In [ ]:
df_sector = df_pura_ciiu['ciiu']
df_sector.unique()

In [ ]:
df_sector_renombrado = df_sector.replace(
    {
        '0': "SinEspecificar",
        0: "SinEspecificar",
        1: "Agricultura",101: "Agricultura",102: "Agricultura",
        103: "Agricultura",104: "Agricultura",
        2: "Agricultura",200: "Agricultura",
        3: "Agricultura",300: "Agricultura",
        5: "Minas",500: "Minas",
        6: "Minas",600: "Minas",
        7: "Minas",700: "Minas",
        8: "Minas",800: "Minas",
        9: "Minas",900: "Minas",
        10: "Industria",1001: "Industria",1002: "Industria",1003: "Industria",1009: "Industria",
        11: "Industria",1100: "Industria",
        12: "Industria",1200: "Industria",
        13: "Industria",1300: "Industria",
        14: "Industria",1400: "Industria",
        15: "Industria",1501: "Industria",1502: "Industria",
        16: "Industria",1600: "Industria",
        17: "Industria",1700: "Industria",
        18: "Industria",1800: "Industria",
        19: "Industria",1901: "Industria",1902: "Industria",
        20: "Industria",2001: "Industria",2002: "Industria",2009: "Industria",
        21: "Industria",
        2100: "Industria",
        22: "Industria",2201: "Industria",2202: "Industria",
        23: "Industria",2301: "Industria",2309: "Industria",
        24: "Industria",2400: "Industria",
        25: "Industria",2500: "Industria",
        26: "Industria",2601: "Industria",2602: "Industria",
        2603: "Industria",2604: "Industria",
        27: "Industria",2701: "Industria",2709: "Industria",
        28: "Industria",2800: "Industria",
        29: "Industria",2900: "Industria",
        30: "Industria",3001: "Industria",3002: "Industria",
        3003: "Industria",3009: "Industria",
        31: "Industria",3100: "Industria",
        32: "Industria",3200: "Industria",
        33: "Industria",3300: "Industria",
        35: "Electricidad",3501: "Electricidad",3502: "Electricidad",
        36: "AguaYSaneamiento",3600: "AguaYSaneamiento",
        37: "AguaYSaneamiento",3700: "AguaYSaneamiento",
        38: "AguaYSaneamiento",3800: "AguaYSaneamiento",
        39: "AguaYSaneamiento",3900: "AguaYSaneamiento",
        40: "Construcción",
        4000: "Construcción",
        45: "Comercio",4501: "Comercio",4502: "Comercio",
        4503: "Comercio",4504: "Comercio",
        48: "Comercio",4801: "Comercio",4802: "Comercio",
        4803: "Comercio",4804: "Comercio",
        4805: "Comercio",4806: "Comercio",4807: "Comercio",4808: "Comercio",
        4809: "Comercio",4810: "Comercio",4811: "Comercio",
        49: "Transporte",4901: "Transporte",4902: "Transporte",
        4903: "Transporte",4904: "Transporte",4905: "Transporte",4909: "Transporte",
        50: "Transporte",5000: "Transporte",
        51: "Transporte",5100: "Transporte",
        52: "Transporte",5201: "Transporte",5202: "Transporte",
        53: "Transporte",5300: "Transporte",
        55: "AlojamientoYComidas",5500: "AlojamientoYComidas",
        56: "AlojamientoYComidas",5602: "AlojamientoYComidas",
        5601: "AlojamientoYComidas",
        58: "InformaciónYComunicaciones",5800: "InformaciónYComunicaciones",
        59: "InformaciónYComunicaciones",5900: "InformaciónYComunicaciones",
        60: "InformaciónYComunicaciones",6000: "InformaciónYComunicaciones",
        61: "InformaciónYComunicaciones",6100: "InformaciónYComunicaciones",
        62: "InformaciónYComunicaciones",6200: "InformaciónYComunicaciones",
        63: "InformaciónYComunicaciones",6300: "InformaciónYComunicaciones",
        64: "FinanzasYSeguros",6400: "FinanzasYSeguros",
        65: "FinanzasYSeguros",6500: "FinanzasYSeguros",
        66: "FinanzasYSeguros",6600: "FinanzasYSeguros",
        68: "Inmobiliarias",6800: "Inmobiliarias",
        69: "Profesionales",6900: "Profesionales",
        70: "Profesionales",7000: "Profesionales",
        71: "Profesionales",7100: "Profesionales",
        72: "Profesionales",7200: "Profesionales",
        73: "Profesionales",7301: "Profesionales",7302: "Profesionales",
        74: "Profesionales",7400: "Profesionales",
        75: "Profesionales",7500: "Profesionales",
        77: "Administrativas",7701: "Administrativas",7702: "Administrativas",
        78: "Administrativas",7800: "Administrativas",
        79: "Administrativas",7900: "Administrativas",
        80: "Administrativas",8000: "Administrativas",
        81: "Administrativas",8101: "Administrativas",8102: "Administrativas",
        82: "Administrativas",8200: "Administrativas",
        83: "AdminPública",
        84: "AdminPública",
        8401: "AdminPública",8402: "AdminPública",
        85: "Enseñanza",8501: "Enseñanza",8509: "Enseñanza",
        86: "Salud",8600: "Salud",
        87: "Salud",8700: "Salud",
        88: "Salud",8800: "Salud",
        90: "Artes",9000: "Artes",
        91: "Artes",9100: "Artes",
        92: "Artes",9200: "Artes",
        93: "Artes",9301: "Artes",9302: "Artes",
        94: "Otras",
        9401: "Otras",9402: "Otras",9409: "Otras",
        95: "Otras",9501: "Otras",9502: "Otras",9503: "Otras",
        96: "Otras",9601: "Otras",9602: "Otras",9603: "Otras",
        9609: "Otras",
        97: "Hogar",
        9700: "Hogar",
        98: "Hogar",
        99: "Extraterritoriales",9900: "Extraterritoriales",
        9999: "Extraterritoriales"
    }       
)

In [ ]:
df_sector_renombrado.unique()

In [ ]:
df_sector_renombrado

In [ ]:
df_conjunta = pd.concat([df_pura, df_sector_renombrado], axis=1)
df_conjunta

In [ ]:
df_arg_final1 = df_conjunta.rename(columns={'sector':"cod_ciiu"})
df_arg_final2 = df_arg_final1.rename(columns={'ciiu':"activity"})
df_arg_final2

In [ ]:
df_pura_final_arg = df_arg_final2[['year', 'quarter','country', 'city', 'employs', 'cod_ciiu', 'activity', 'salary']]
df_pura_final_arg

Reseteamos el índice para dejarla pulpa

In [ ]:
df_final = df_pura_final_arg.reset_index(drop=True)
df_final

Guardamos la base de datos de Argentina depurada entre 2017 y 2021

In [ ]:
df_final.to_csv('ArgBD2T2017_2021')

Anexos

In [ ]:
#BD_Depur_Ocu_Ciudad_Sector = BD_Depur_Ocu_Ciudad.replace(
    {'sector': {
        01: "Agricultura",
        02: "Agricultura",
        03: "Agricultura",
        05: "Minas",
        06: "Minas",
        07: "Minas",
        08: "Minas",
        09: "Minas",
        10: "Industria",
        11: "Industria",
        12: "Industria",
        13: "Industria",
        14: "Industria",
        15: "Industria",
        16: "Industria",
        17: "Industria",
        18: "Industria",
        19: "Industria",
        20: "Industria",
        21: "Industria",
        22: "Industria",
        23: "Industria",
        24: "Industria",
        25: "Industria",
        26: "Industria",
        27: "Industria",
        28: "Industria",
        29: "Industria",
        30: "Industria",
        31: "Industria",
        32: "Industria",
        33: "Industria",
        35: "Electricidad",
        36: "AguaYSaneamiento",
        37: "AguaYSaneamiento",
        38: "AguaYSaneamiento",
        39: "AguaYSaneamiento",
        40: "Construcción",
        45: "Comercio",
        48: "Comercio",
        49: "Transporte",
        50: "Transporte",
        51: "Transporte",
        52: "Transporte",
        53: "Transporte",
        55: "AlojamientoYComidas",
        56: "AlojamientoYComidas",
        58: "InformaciónYComunicaciones",
        59: "InformaciónYComunicaciones",
        60: "InformaciónYComunicaciones",
        61: "InformaciónYComunicaciones",
        62: "InformaciónYComunicaciones",
        63: "InformaciónYComunicaciones",
        64: "FinanzasYSeguros",
        65: "FinanzasYSeguros",
        66: "FinanzasYSeguros",
        68: "Inmobiliarias",
        69: "Profesionales",
        70: "Profesionales",
        71: "Profesionales",
        72: "Profesionales",
        73: "Profesionales",
        74: "Profesionales",
        75: "Profesionales",
        77: "Administrativas",
        78: "Administrativas",
        79: "Administrativas",
        80: "Administrativas",
        81: "Administrativas",
        82: "Administrativas",
        83: "AdminPública",
        84: "AdminPública",
        85: "Enseñanza",
        86: "Salud",
        87: "Salud",
        88: "Salud",
        90: "Artes",
        91: "Artes",
        92: "Artes",
        93: "Artes",
        94: "Otras",
        95: "Otras",
        96: "Otras",
        97: "Hogar",
        98: "Hogar",
        99: "Extraterritoriales"}       
    }
)