##0.Cargar DataFrames de México 2T desde 2017 hasta 2021

Tareas reu 22 de noviembre

Un nuevo colab: de ciudades y sectores por trimestre

Calculo Shit_Share
Por ciudad, total por ciudad y contrastar total Nacional
Por sector, total por ciudad y contrastar total Nacional

In [115]:
import pandas as pd
import numpy as np

In [116]:
from google.colab import drive
drive.mount('/content/drive/')
!ls

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
 2017trim1_csv.zip   coe2t120.csv
 2017trim2_csv.zip   coe2t217.CSV
 2017trim3_csv.zip   coe2t218.csv
 2017trim4_csv.zip   COE2T219.csv
 2018trim1_csv.zip   coe2t317.CSV
 2018trim2_csv.zip   coe2t318.csv
 2018trim3_csv.zip   COE2T319.csv.CSV
 2018trim4_csv.zip   coe2t417.CSV
 2019trim1_csv.zip   COE2T418.csv
 2019trim2_csv.zip   COE2T419.CSV
 2019trim3_csv.zip   enoe_n_2020_trim3_csv.zip
 2019trim4_csv.zip   enoe_n_2020_trim4_csv.zip
 2020trim1_csv.zip   enoe_n_2021_trim1_csv.zip
 coe1t117.CSV	     ENOEN_COE1T121.csv
 COE1T118.CSV	     ENOEN_COE1T221.csv
 coe1t119.csv	     ENOEN_COE1T320.csv
 coe1t120.csv	     ENOEN_coe1t420.csv
 coe1t217.CSV	     ENOEN_COE2T121.csv
 coe1t218.csv	     ENOEN_COE2T221.csv
 COE1T219.csv	     ENOEN_COE2T320.csv
 coe1t317.CSV	     ENOEN_coe2t420.csv
 coe1t318.csv	    'Metodología México Microdatos con_basedatos_proy2010.pdf'
 COE1T319.csv.CSV    MexBD2T2017_2021
 coe1t417.CSV	    'MEXICO MICRODATO enoe_n_2021_trim2_csv.zip'
 COE1T418.csv	     nota_bases_datos_enoe_2020_1t.txt
 COE1T419.CSV	     nota_bases_datos_enoen_2020_3t.txt
 coe2t117.CSV	     nota_bases_datos_enoen_2021_1t.txt
 COE2T118.CSV	     nota_bases_datos_enoen_2021_2t.txt
 coe2t119.csv

In [117]:
%cd'/content/drive/My Drive/BID Ciudades/MicroDatos/Mexico'
!ls

/content/drive/My Drive/BID Ciudades/MicroDatos/Mexico
 2017trim1_csv.zip   coe2t120.csv
 2017trim2_csv.zip   coe2t217.CSV
 2017trim3_csv.zip   coe2t218.csv
 2017trim4_csv.zip   COE2T219.csv
 2018trim1_csv.zip   coe2t317.CSV
 2018trim2_csv.zip   coe2t318.csv
 2018trim3_csv.zip   COE2T319.csv.CSV
 2018trim4_csv.zip   coe2t417.CSV
 2019trim1_csv.zip   COE2T418.csv
 2019trim2_csv.zip   COE2T419.CSV
 2019trim3_csv.zip   enoe_n_2020_trim3_csv.zip
 2019trim4_csv.zip   enoe_n_2020_trim4_csv.zip
 2020trim1_csv.zip   enoe_n_2021_trim1_csv.zip
 coe1t117.CSV	     ENOEN_COE1T121.csv
 COE1T118.CSV	     ENOEN_COE1T221.csv
 coe1t119.csv	     ENOEN_COE1T320.csv
 coe1t120.csv	     ENOEN_coe1t420.csv
 coe1t217.CSV	     ENOEN_COE2T121.csv
 coe1t218.csv	     ENOEN_COE2T221.csv
 COE1T219.csv	     ENOEN_COE2T320.csv
 coe1t317.CSV	     ENOEN_coe2t420.csv
 coe1t318.csv	    'Metodología México Microdatos con_basedatos_proy2010.pdf'
 COE1T319.csv.CSV    MexBD2T2017_2021
 coe1t417.CSV	    'MEXICO MICRODATO enoe_n_2021_trim2_csv.zip'
 COE1T418.csv	     nota_bases_datos_enoe_2020_1t.txt
 COE1T419.CSV	     nota_bases_datos_enoen_2020_3t.txt
 coe2t117.CSV	     nota_bases_datos_enoen_2021_1t.txt
 COE2T118.CSV	     nota_bases_datos_enoen_2021_2t.txt
 coe2t119.csv

In [118]:
path = '/content/drive/MyDrive/BID Ciudades/MicroDatos/Mexico/MexBD2T2017_2021'
dfMEX = pd.read_csv(path)
dfMEX

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2,3,5) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

         Unnamed: 0  ocupados ciudad  ... Trimestre  factor_trim factor_men
0                 0         1      9  ...      2017          NaN        NaN
1                 1         2      9  ...      2017          NaN        NaN
2                 2         1      9  ...      2017          NaN        NaN
3                 3         2      9  ...      2017          NaN        NaN
4                 4         1      9  ...      2017          NaN        NaN
...             ...       ...    ...  ...       ...          ...        ...
1252664      307467         1      7  ...      2021         46.0        0.0
1252665      307468         2      7  ...      2021         46.0        0.0
1252666      307469         1      7  ...      2021         46.0        0.0
1252667      307470         1      7  ...      2021         46.0        0.0
1252668      307471         2      7  ...      2021         46.0        0.0

[1252669 rows x 9 columns]

In [119]:
dfMEX['ocupados'].value_counts()

1    658469
2    594200
Name: ocupados, dtype: int64

Que en la depuración inicial del COLAB venga con los expansivos
Crear una variable llamada OCU: número de ocupados ya multiplicados por el factor de expansión, lo demás es cero


Crear una variable numerica de multiplicación por factor

##1.Preprocesamiento para poder hacer los cálculos

Necesitamos todas las columnas como float para hacer matemáticas

In [98]:
import sklearn

In [99]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer

In [94]:
dfMEX.dtypes

Unnamed: 0       int64
ocupados         int64
ciudad          object
sector          object
factor         float64
salario         object
Trimestre        int64
factor_trim    float64
factor_men     float64
dtype: object

In [96]:
dfMEX['ocupados'] = dfMEX.ocupados.astype(float)

In [97]:
dfMEX.dtypes

Unnamed: 0       int64
ocupados       float64
ciudad          object
sector          object
factor         float64
salario         object
Trimestre        int64
factor_trim    float64
factor_men     float64
dtype: object

In [109]:
dfMEX.ciudad.describe

<bound method NDFrame.describe of 0          9
1          9
2          9
3          9
4          9
          ..
1252664    7
1252665    7
1252666    7
1252667    7
1252668    7
Name: ciudad, Length: 1252669, dtype: object>

In [112]:
dfMEX['ciudad'] = dfMEX.ciudad.convert_dtypes(convert_boolean=True)

In [114]:
dfMEX.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1252669 entries, 0 to 1252668
Data columns (total 9 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Unnamed: 0   1252669 non-null  int64
 1   ocupados     1252669 non-null  float64
 2   ciudad       1252669 non-null  object
 3   sector       973333 non-null   object
 4   factor       945197 non-null   float64
 5   salario      986107 non-null   object
 6   Trimestre    1252669 non-null  int64
 7   factor_trim  307472 non-null   float64
 8   factor_men   307472 non-null   float64
dtypes: float64(4), int64(2), object(3)
memory usage: 86.0+ MB

In [104]:
pd.to_numeric(dfMEX['ciudad'], errors='ignore')

0          9
1          9
2          9
3          9
4          9
          ..
1252664    7
1252665    7
1252666    7
1252667    7
1252668    7
Name: ciudad, Length: 1252669, dtype: object

In [111]:
dfMEX['ciudad'] = dfMEX.ciudad.astype(float)

ValueError: ignored

In [107]:
v1= lambda x:float(x[1:-1])

In [108]:
dfMEX.ciudad = dfMEX.ciudad.apply(v1)

TypeError: ignored

In [105]:
dfMEX.dtypes

Unnamed: 0       int64
ocupados       float64
ciudad          object
sector          object
factor         float64
salario         object
Trimestre        int64
factor_trim    float64
factor_men     float64
dtype: object

HACER EXPANSIONES

In [91]:
dfMEX.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1252669 entries, 0 to 1252668
Data columns (total 9 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Unnamed: 0   1252669 non-null  int64
 1   ocupados     1252669 non-null  float64
 2   ciudad       1252669 non-null  object
 3   sector       973333 non-null   object
 4   factor       945197 non-null   float64
 5   salario      986107 non-null   object
 6   Trimestre    1252669 non-null  int64
 7   factor_trim  307472 non-null   float64
 8   factor_men   307472 non-null   float64
dtypes: float64(4), int64(2), object(3)
memory usage: 86.0+ MB

In [70]:
dfMEX.dtypes

Unnamed: 0       int64
ocupados         int64
ciudad          object
sector          object
factor         float64
salario         object
Trimestre        int64
factor_trim    float64
factor_men     float64
dtype: object

In [77]:
dfMEX['ocupados'] = dfMEX.ocupados.astype(float)

In [88]:
dfMEX['ciudad'].describe

<bound method NDFrame.describe of 0          9
1          9
2          9
3          9
4          9
          ..
1252664    7
1252665    7
1252666    7
1252667    7
1252668    7
Name: ciudad, Length: 1252669, dtype: object>

In [89]:
dfMEX.ciudad.str.contains('1').astype(int).head()

ValueError: ignored

In [87]:
dfMEX['ciudad'] = dfMEX.ciudad.astype(float)

ValueError: ignored

In [78]:
dfMEX.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1252669 entries, 0 to 1252668
Data columns (total 9 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Unnamed: 0   1252669 non-null  int64
 1   ocupados     1252669 non-null  float64
 2   ciudad       1252669 non-null  object
 3   sector       973333 non-null   object
 4   factor       945197 non-null   float64
 5   salario      986107 non-null   object
 6   Trimestre    1252669 non-null  int64
 7   factor_trim  307472 non-null   float64
 8   factor_men   307472 non-null   float64
dtypes: float64(4), int64(2), object(3)
memory usage: 86.0+ MB

In [84]:
dfMEX['ciudad'].value_counts()

15    42266
5     39724
11    39331
14    33956
21    33546
      ...
9      6970
6      6926
12     5962
3      5722
15     1287
Name: ciudad, Length: 65, dtype: int64

In [80]:
dfMEX['ocupados'].describe()

count    1.252669e+06
mean     1.474347e+00
std      4.993417e-01
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      2.000000e+00
max      2.000000e+00
Name: ocupados, dtype: float64

In [54]:
dfMEX['sector'].value_counts()

          283732
7221       23078
1110       21754
7221.0     21525
1110.0     18757
           ...
5412.0         1
4370.0         1
4810.0         1
5120.0         1
4820.0         1
Name: sector, Length: 471, dtype: int64

In [86]:
dfMEX['ciudad'].value_counts()

15    42266
5     39724
11    39331
14    33956
21    33546
      ...
9      6970
6      6926
12     5962
3      5722
15     1287
Name: ciudad, Length: 65, dtype: int64

In [81]:
df_ocupado = dfMEX['ocupados']
df_ocupado

0          1.0
1          2.0
2          1.0
3          2.0
4          1.0
          ...
1252664    1.0
1252665    2.0
1252666    1.0
1252667    1.0
1252668    2.0
Name: ocupados, Length: 1252669, dtype: float64

##1.Ocupación por Ciudad

In [62]:
#meta ejemplo
df_ocu_ciudad = pd.DataFrame(
    [['2017', 'CDMX', '5'], ['2017', 'Monterrey', '6']],
    [columns=['año', 'ciudad', 'ocupados']])

SyntaxError: ignored

In [23]:
dfMEX

         Unnamed: 0 ocupados ciudad  ... factor_trim  factor_men Expandidos
0                 0        1      9  ...         NaN         NaN      648.0
1                 1        1      9  ...         NaN         NaN     1296.0
2                 2        1      9  ...         NaN         NaN      648.0
3                 3        1      9  ...         NaN         NaN     1296.0
4                 4        1      9  ...         NaN         NaN      648.0
...             ...      ...    ...  ...         ...         ...        ...
1252664      307467        1      7  ...        46.0         0.0        NaN
1252665      307468        1      7  ...        46.0         0.0        NaN
1252666      307469        1      7  ...        46.0         0.0        NaN
1252667      307470        1      7  ...        46.0         0.0        NaN
1252668      307471        1      7  ...        46.0         0.0        NaN

[1252669 rows x 10 columns]

In [24]:
dfMEX['ocupados'] == '1'

0          True
1          True
2          True
3          True
4          True
           ...
1252664    True
1252665    True
1252666    True
1252667    True
1252668    True
Name: ocupados, Length: 1252669, dtype: bool

In [8]:
dfMEX['sector'].value_counts()

          283732
7221       23078
1110       21754
7221.0     21525
1110.0     18757
           ...
5412.0         1
4370.0         1
4810.0         1
5120.0         1
4820.0         1
Name: sector, Length: 471, dtype: int64

In [7]:
dfMEX['ciudad'].value_counts()

15    42266
5     39724
11    39331
14    33956
21    33546
      ...
9      6970
6      6926
12     5962
3      5722
15     1287
Name: ciudad, Length: 65, dtype: int64

##2.Ocupación por Sector

##3.Validación de resultados