#Pre Configuración

In [1]:
import pandas as pd
pd.__version__

from google.colab import drive
drive.mount('/content/drive/')
!ls

Mounted at /content/drive/
drive  sample_data

In [50]:
import numpy as np

#Carga data Latam

In [2]:
path1 = '/content/drive/Shareddrives/BID/Ciudades/Metadatos/Consolidado micro_meta-20.01.22.xlsx'
df1_consolidados = pd.read_excel(path1)
df1_consolidados

          País         Región   ...    Ocupados     Salario
0        Panamá  Centroamérica  ...     1785849         NaN
1        Panamá  Centroamérica  ...      258831         NaN
2        Panamá  Centroamérica  ...        4167         NaN
3        Panamá  Centroamérica  ...      131214         NaN
4        Panamá  Centroamérica  ...        5133         NaN
...         ...            ...  ...         ...         ...
10188  Colombia    Sudamérica   ...  1894138989  8916493026
10189  Colombia    Sudamérica   ...  1420141178  7948704673
10190  Colombia    Sudamérica   ...  9890000371  8640746802
10191  Colombia    Sudamérica   ...  2477745566  5656565998
10192  Colombia    Sudamérica   ...  1553229364  8566070856

[10193 rows x 8 columns]

#Limpieza de datos

In [3]:
df1_consolidados['Sector_renombrado'].unique()

array(['Total', 'Agricultura', 'Manufactura', 'Servicios', 'Construcción',
       'Comercio', 'Transporte', 'Alojamiento', 'Telecomunicaciones',
       'Actividades Financieras', 'NS/NR', 'Comercio y Alojamiento',
       'Industria', 'servicios', 'SinDefinir'], dtype=object)

In [3]:
#renombrar las observaciones de sectores manera estandarizada
df_consolidados = df1_consolidados["Sector_renombrado"].replace(["servicios"], "Servicios")

In [5]:
df_consolidados.unique()

array(['Total', 'Agricultura', 'Manufactura', 'Servicios', 'Construcción',
       'Comercio', 'Transporte', 'Alojamiento', 'Telecomunicaciones',
       'Actividades Financieras', 'NS/NR', 'Comercio y Alojamiento',
       'Industria', 'SinDefinir'], dtype=object)

In [4]:
df = df_consolidados.replace(["NS/NR"], "SinDefinir")

In [7]:
df.unique()

array(['Total', 'Agricultura', 'Manufactura', 'Servicios', 'Construcción',
       'Comercio', 'Transporte', 'Alojamiento', 'Telecomunicaciones',
       'Actividades Financieras', 'SinDefinir', 'Comercio y Alojamiento',
       'Industria'], dtype=object)

In [10]:
df

0                     Total
1               Agricultura
2               Agricultura
3               Manufactura
4                 Servicios
                ...
10188          Construcción
10189           Manufactura
10190             Servicios
10191    Telecomunicaciones
10192            Transporte
Name: Sector_renombrado, Length: 10193, dtype: object

In [5]:
df1_consolidados['Sector'] = df
df1_consolidados

          País         Región   ...     Salario              Sector
0        Panamá  Centroamérica  ...         NaN               Total
1        Panamá  Centroamérica  ...         NaN         Agricultura
2        Panamá  Centroamérica  ...         NaN         Agricultura
3        Panamá  Centroamérica  ...         NaN         Manufactura
4        Panamá  Centroamérica  ...         NaN           Servicios
...         ...            ...  ...         ...                 ...
10188  Colombia    Sudamérica   ...  8916493026        Construcción
10189  Colombia    Sudamérica   ...  7948704673         Manufactura
10190  Colombia    Sudamérica   ...  8640746802           Servicios
10191  Colombia    Sudamérica   ...  5656565998  Telecomunicaciones
10192  Colombia    Sudamérica   ...  8566070856          Transporte

[10193 rows x 9 columns]

In [9]:
df1_consolidados['Ciudad'].unique()

array(['Total Nacional', 'Ciudad Panamá', 'Panamá Oeste',
       'Bocas del Toro', 'Colón', 'Coclé', 'CHIRIQUI', 'Darien',
       'Herrera', 'Los Santos', 'Veraguas', 'Comarca Kuna Yala',
       'Comarca Emberá', 'Comarca Ngabe Buble', 'New Providence',
       'Grand Bahama', 'Abaco', 'Total Nacional Urbano', 'La Paz',
       'Cochabamba', 'Santa Cruz', 'Otros', 'Total Nacional ', 'Urbano',
       'Distrito Central', 'San Pedro Sula', 'Resto urbano',
       'Sin Especificar', 'AZUAY - CUENCA', 'BOLIVAR - GUARANDA',
       'CARCHI - TULCAN', 'CAÑAR - AZOGUES', 'CHIMBORAZO - RIOBAMBA',
       'COTOPAXI - LATACUNGA', 'EL ORO - MACHALA',
       'ESMERALDAS - ESMERALDAS', 'GUAYAS - GUAYAQUIL',
       'IMBABURA - IBARRA', 'LOJA - LOJA', 'LOS RIOS - BABAHOYO',
       'MANABI - PORTOVIEJO', 'MORONA SANTIAGO - MORONA', 'NAPO - TENA',
       'ORELLANA - ORELLANA', 'PASTAZA - PASTAZA', 'PICHINCHA - QUITO',
       'SANTA ELENA - SANTA ELENA',
       'SANTO DOMINGO DE LOS TSACHILAS - SANTO DOMINGO',
       'SUCUMBIOS - LAGO AGRIO', 'TUNGURAHUA - AMBATO',
       'ZAMORA CHINCHIPE - ZAMORA',
       'Región Administrativa Integrada de Desenvolvimento da Grande Teresina (PI)',
       'Región Metropolitana de Aracaju (SE)',
       'Región Metropolitana de Belo Horizonte (MG)',
       'Región Metropolitana de Belém (PA)',
       'Región Metropolitana de Curitiba (PR)',
       'Región Metropolitana de Florianópolis (SC)',
       'Región Metropolitana de Fortaleza (CE)',
       'Región Metropolitana de Goiânia (GO)',
       'Región Metropolitana de Grande São Luís (MA)',
       'Región Metropolitana de Grande Vitória (ES)',
       'Región Metropolitana de João Pessoa (PB)',
       'Región Metropolitana de Macapá (AP)',
       'Región Metropolitana de Maceió (AL)',
       'Región Metropolitana de Manaus (AM)',
       'Región Metropolitana de Natal (RN)',
       'Región Metropolitana de Porto Alegre (RS)',
       'Región Metropolitana de Recife (PE)',
       'Región Metropolitana de Rio de Janeiro (RJ)',
       'Región Metropolitana de Salvador (BA)',
       'Región Metropolitana de São Paulo (SP)',
       'Región Metropolitana de Vale do Rio Cuiabá (MT)', 'Brunca',
       'Central', 'Chorotega', 'Huetar Atlántica', 'Huetar Norte',
       'Pacífico Central', 'Ciudades Medianas', 'Ciudades Pequeñas',
       'Bahía Blanca', 'Buenos Aires', 'Catamarca', 'Concordia',
       'Corrientes', 'Córdoba', 'Estero', 'Formosa', 'Gallegos', 'Jujuy',
       'La Plata', 'Mar del Plata', 'Mendoza', 'Neuquén', 'Paraná',
       'Partidos del Gran Buenos Aires', 'Posadas', 'Rawson',
       'Resistencia', 'Rioja', 'Rivadavia', 'Rosario', 'Río Cuarto',
       'Salta', 'San Juan', 'San Luis', 'San Nicolás', 'Santa Fé',
       'Santa Rosa', 'Tucumán', 'Ushuaia', 'Viedma',
       'Antofagasta - Antofagasta', 'Araucanía - Temuco', 'Arica - Arica',
       'Atacama - Copiapó', 'Aysén - Coyhaique', 'Biobío - Concepción',
       'Coquimbo - La Serena', 'Lagos - Puerto Montt',
       'Magallanes - Punta Arenas', 'Maule - Talca',
       'Metropolitana - Santiago de Chile', "O'Higgins - Rancagua",
       'Ríos - Valdivia', 'Tarapacá - Iquique', 'Valparaiso- Valparaíso',
       'Ñuble - Chillán', 'Ahuachapán, Santa Ana y Sonsonate.',
       'Chalatenango,La Libertad, San Salvador y Cuscatlán.',
       'Cuscatancingo, Soyapango, Mejicanos, San Salvador, Ayutuxtepeque, San Marcos, Delgado, Ilopango, Apopa, Antiguo, Cuscatlán, San Martín, Santa Tecla, Tonacatepeque, Nejapa',
       'La Paz, Cabañas y San Vicente.',
       'Usulután, San Miguel, Morazán y La Unión', 'Alto Paraná',
       'Asunción', 'Caaguazú', 'Caazapá', 'Itapúa', 'San Pedro', 'Resto',
       'Interior, localidades urbanas de 5000 habitantes o más',
       'Interior, localidades urbanas de menos de 5000 habitantes',
       'Montevideo', 'RESTO URBANO', 'URBANO METROPOLITANO',
       'Cibao Nordeste Urbano', 'Cibao Noroeste Urbano',
       'Cibao Sur Urbano', 'Distrito Nacional', 'El Valle Urbano',
       'Enriquillo Urbano', 'Higuamo Urbano', 'Resto Cibao Norte Urbano',
       'Santiago Urbano', 'Santo Domingo Urbano', 'Valdesia Urbano',
       'Yuma Urbano', 'Lima Metropolitana', 'Acapulco', 'Aguascalientes',
       'CDMX Metropolitana', 'Campeche', 'Cancún', 'Chihuahua', 'Colima',
       'Cuernavaca', 'Culiacán', 'Durango', 'Guadalajara', 'Hermosillo',
       'León', 'Monterrey', 'Morelia', 'Mérida', 'Oaxaca', 'Pachuca',
       'Puebla', 'Querétaro', 'Saltillo', 'San Luis de Potosí', 'Tampico',
       'Tepic', 'Tijuana', 'Tlaxcala', 'Toluca', 'Torreón',
       'Tuxtla Gutierrez', 'Veracruz', 'Villahermosa', 'Zacatecas',
       'ARMENIA', 'BARRANQUILLA', 'BOGOTA, D.C.', 'BUCARAMANGA', 'CALI',
       'CARTAGENA', 'CUCUTA', 'FLORENCIA', 'IBAGUE', 'MANIZALES',
       'MEDELLIN', 'MONTERIA', 'NEIVA', 'PASTO', 'PEREIRA', 'POPAYAN',
       'QUIBDO', 'RIOHACHA', 'SANTA MARTA', 'SINCELEJO', 'TUNJA',
       'VALLEDUPAR', 'VILLAVICENCIO'], dtype=object)

In [6]:
#Paso: Quitar las columnas no necesarias 
df_pre_shift_share = df1_consolidados.drop(['Sector_renombrado', 'Salario'], axis=1)
df_pre_shift_share

          País         Región   ...    Ocupados              Sector
0        Panamá  Centroamérica  ...     1785849               Total
1        Panamá  Centroamérica  ...      258831         Agricultura
2        Panamá  Centroamérica  ...        4167         Agricultura
3        Panamá  Centroamérica  ...      131214         Manufactura
4        Panamá  Centroamérica  ...        5133           Servicios
...         ...            ...  ...         ...                 ...
10188  Colombia    Sudamérica   ...  1894138989        Construcción
10189  Colombia    Sudamérica   ...  1420141178         Manufactura
10190  Colombia    Sudamérica   ...  9890000371           Servicios
10191  Colombia    Sudamérica   ...  2477745566  Telecomunicaciones
10192  Colombia    Sudamérica   ...  1553229364          Transporte

[10193 rows x 7 columns]

In [7]:
#Paso b: Quitar los totales nacionales y todos sector para evitar doble contabilidad
#'Total Nacional'
#'Total Nacional Urbano'
#'Total Nacional '
#'Total'
df_pre_shift_share = df_pre_shift_share.drop(df_pre_shift_share[df_pre_shift_share['Ciudad']=='Total Nacional'].index)
df_pre_shift_share = df_pre_shift_share.drop(df_pre_shift_share[df_pre_shift_share['Ciudad']=='Total Nacional Urbano'].index)
df_pre_shift_share = df_pre_shift_share.drop(df_pre_shift_share[df_pre_shift_share['Ciudad']=='Total Nacional '].index)
df_pre_shift_share = df_pre_shift_share.drop(df_pre_shift_share[df_pre_shift_share['Sector']=='Total'].index)
df_pre_shift_share

          País         Región   ...    Ocupados              Sector
23       Panamá  Centroamérica  ...       14751         Agricultura
24       Panamá  Centroamérica  ...         324         Agricultura
25       Panamá  Centroamérica  ...       53132         Manufactura
26       Panamá  Centroamérica  ...        2215           Servicios
27       Panamá  Centroamérica  ...        6916           Servicios
...         ...            ...  ...         ...                 ...
10188  Colombia    Sudamérica   ...  1894138989        Construcción
10189  Colombia    Sudamérica   ...  1420141178         Manufactura
10190  Colombia    Sudamérica   ...  9890000371           Servicios
10191  Colombia    Sudamérica   ...  2477745566  Telecomunicaciones
10192  Colombia    Sudamérica   ...  1553229364          Transporte

[9347 rows x 7 columns]

In [8]:
#Paso: Agrupar los sectores repetidos en periodo para la misma ciudad
df_pre_shift_share_final = df_pre_shift_share.groupby(['Sector', 'Ciudad', 'Año', 'Ocupados'], as_index=False).sum()
df_pre_shift_share_final

                       Sector           Ciudad  ...      Región  Periodo
0     Actividades Financieras          ARMENIA  ...  Sudamérica    junio
1     Actividades Financieras          ARMENIA  ...  Sudamérica    junio
2     Actividades Financieras          ARMENIA  ...  Sudamérica    junio
3     Actividades Financieras          ARMENIA  ...  Sudamérica    junio
4     Actividades Financieras          ARMENIA  ...  Sudamérica    junio
...                       ...              ...  ...          ...     ...
9266               Transporte  Ñuble - Chillán  ...   Sudamérica   junio
9267               Transporte  Ñuble - Chillán  ...   Sudamérica   junio
9268               Transporte  Ñuble - Chillán  ...   Sudamérica   junio
9269               Transporte  Ñuble - Chillán  ...   Sudamérica   junio
9270               Transporte  Ñuble - Chillán  ...   Sudamérica   junio

[9271 rows x 7 columns]

In [9]:
df_pre_shift_share_final = df_pre_shift_share_final[['Año', 'Periodo', 'Región ', 'País ', 'Ciudad', 'Sector', 'Ocupados']]
df_pre_shift_share_final

       Año Periodo  ...                   Sector    Ocupados
0     2017   junio  ...  Actividades Financieras  6124354202
1     2018   junio  ...  Actividades Financieras   523132773
2     2019   junio  ...  Actividades Financieras  5079108064
3     2020   junio  ...  Actividades Financieras  1457182046
4     2021   junio  ...  Actividades Financieras  1798341276
...    ...     ...  ...                      ...         ...
9266  2017   junio  ...               Transporte     390.085
9267  2018   junio  ...               Transporte     1292.13
9268  2019   junio  ...               Transporte     941.012
9269  2020   junio  ...               Transporte     1642.27
9270  2021   junio  ...               Transporte     1233.47

[9271 rows x 7 columns]

#Parámetros Shift Share

1) National Share
2) Regional Share
3) Industry Mix

Temporalidades a calcular: <br>
a) Primer periodo Vs último periodo <br>
b1) bloque pre covid (promedio 2019 y antes) Vs post covid (promedio 2020 en adelante) <br>
b2) bloque pre covid (promedio 2019 y antes) Vs último dato post 2020

National Share (NS): <br> NS_t_sector_ciudad = ocupados_t-1_sector_ciudad x ((ocupados_t_pais / ocupados_t-1_pais)-1)

In [ ]:
#POR PAÍS, SECTOR Y CIUDAD: 
#NS_t_sector_ciudad = a*((b/c)-1)
#a: ocupados_t-1_sector_ciudad
#b: ocupados_t_pais
#c: ocupados_t-1_pais

Industry mix (IM) <br>
Imix_t_sector_ciudad = ocupados_t-1_sector_ciudad * ((ocupados_t_sector_pais/ocupados_t-1_sector_pais)-(ocupados_t_pais/ocupados_t-1_pais))

In [ ]:
#POR PAÍS, SECTOR Y CIUDAD: 
#IM_t_sector_ciudad = a*((d/e)-(b/c))
#a: ocupados_t-1_sector_ciudad
#d: ocupados_t_sector_pais
#e: ocupados_t-1_sector_pais
#b: ocupados_t_pais
#c: ocupados_t-1_pais

Regional Shift (RS): <br>
RS_t_sector_ciudad = ocupados_t-1_sector_ciudad * ((ocupados_t_sector_ciudad/ocupados_t-1_sector_ciudad)-(ocupados_t_sector_pais/ocupados_t-1_sector_país))

In [ ]:
#POR PAIS, SECTOR Y CIUDAD: 
#RS_t_sector_ciudad = a*((f/a)-(d/e))
#a: ocupados_t-1_sector_ciudad
#f: ocupados_t_sector_ciudad
#a: ocupados_t-1_sector_ciudad
#d: ocupados_t_sector_pais
#e: ocupados_t-1_sector_pais

Listado de las 6 variables requeridas

In [ ]:
#a: ocupados_t-1_sector_ciudad
#b: ocupados_t_pais
#c: ocupados_t-1_pais
#d: ocupados_t_sector_pais
#e: ocupados_t-1_sector_pais
#f: ocupados_t_sector_ciudad

Fórmulas resumidas

In [ ]:
#NS = a*((b/c)-1)
#IM = a*((d/e)-(b/c))
#RS = a*((f/a)-(d/e))

#Cálculos Shift Share

#Alistamiento de datos

2019 Vs 2020: alistamiento de años

In [10]:
df2019 = df_pre_shift_share_final.drop(df_pre_shift_share_final[df_pre_shift_share_final['Año']!=2019].index)
df2019 = df2019.rename(columns={'Ocupados': 'Ocupados2019'})
df2019

       Año Periodo  ...                   Sector Ocupados2019
2     2019   junio  ...  Actividades Financieras   5079108064
7     2019   junio  ...  Actividades Financieras      3418.67
12    2019   anual  ...  Actividades Financieras         4751
16    2019   anual  ...  Actividades Financieras        26179
20    2019   junio  ...  Actividades Financieras       390.23
...    ...     ...  ...                      ...          ...
9250  2019      2T  ...               Transporte         3565
9254  2019   junio  ...               Transporte          959
9259  2019   anual  ...               Transporte      71265.9
9264  2019   junio  ...               Transporte      213.083
9268  2019   junio  ...               Transporte      941.012

[1982 rows x 7 columns]

In [11]:
df2020 = df_pre_shift_share_final.drop(df_pre_shift_share_final[df_pre_shift_share_final['Año']!=2020].index)
df2020 = df2020.rename(columns={'Ocupados': 'Ocupados2020'})
df2020

       Año    Periodo  ...                   Sector Ocupados2020
3     2020      junio  ...  Actividades Financieras   1457182046
8     2020  noviembre  ...  Actividades Financieras      2874.05
13    2020      anual  ...  Actividades Financieras      5331.27
17    2020      anual  ...  Actividades Financieras        27069
19    2020      junio  ...  Actividades Financieras      165.686
...    ...        ...  ...                      ...          ...
9241  2020      anual  ...               Transporte       107476
9246  2020      junio  ...               Transporte      3362.24
9255  2020      junio  ...               Transporte          347
9260  2020      anual  ...               Transporte      98749.7
9269  2020      junio  ...               Transporte      1642.27

[1602 rows x 7 columns]

Tabla Merge 2019_2020

In [12]:
df_ss_19_20 = df2019.merge(df2020, how="left", left_on=["País ", "Ciudad", "Sector"], right_on=["País ", "Ciudad", "Sector"])
df_ss_19_20 = df_ss_19_20.drop(['Año_x', 'Periodo_x', "Región _x",'Año_y', 'Periodo_y', "Región _y"], axis=1)
df_ss_19_20

                     País   ... Ocupados2020
0                 Colombia  ...   1457182046
1                  Ecuador  ...      2874.05
2              El Salvador  ...      5331.27
3                 Paraguay  ...        27069
4                    Chile  ...          NaN
...                    ...  ...          ...
2288                Panamá  ...          NaN
2289             Argentina  ...          347
2290  República Dominicana  ...      98749.7
2291               Ecuador  ...          NaN
2292                 Chile  ...      1642.27

[2293 rows x 5 columns]

In [15]:
#quitando las observaciones en cero y con NaN para poder hacer las divisiones
df_ss_19_20_final = df_ss_19_20.drop(df_ss_19_20[df_ss_19_20['Ocupados2019']==0].index)
df_ss_19_20_final

                     País   ... Ocupados2020
0                 Colombia  ...   1457182046
1                  Ecuador  ...      2874.05
2              El Salvador  ...      5331.27
3                 Paraguay  ...        27069
4                    Chile  ...          NaN
...                    ...  ...          ...
2288                Panamá  ...          NaN
2289             Argentina  ...          347
2290  República Dominicana  ...      98749.7
2291               Ecuador  ...          NaN
2292                 Chile  ...      1642.27

[2267 rows x 5 columns]

In [16]:
#quitando los NaN
df_ss_19_20_final = df_ss_19_20_final.dropna()
df_ss_19_20_final

                     País   ... Ocupados2020
0                 Colombia  ...   1457182046
1                  Ecuador  ...      2874.05
2              El Salvador  ...      5331.27
3                 Paraguay  ...        27069
5                 Paraguay  ...        35549
...                    ...  ...          ...
2286  República Dominicana  ...       107476
2287                 Chile  ...      3362.24
2289             Argentina  ...          347
2290  República Dominicana  ...      98749.7
2292                 Chile  ...      1642.27

[1896 rows x 5 columns]

In [25]:
df_ss_19_20_final['Ocupados2020'].describe

<bound method NDFrame.describe of 0       1457182046
1          2874.05
2          5331.27
3            27069
5            35549
           ...
2286        107476
2287       3362.24
2289           347
2290       98749.7
2292       1642.27
Name: Ocupados2020, Length: 1896, dtype: object>

In [32]:
#ajustando los formatos a numéricos
df_ss_19_20_final[['Ocupados2019']].replace({"161628,23": "161628.23"}, inplace=True)
df_ss_19_20_final

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4389: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

                     País   ... Ocupados2020
0                 Colombia  ...   1457182046
1                  Ecuador  ...      2874.05
2              El Salvador  ...      5331.27
3                 Paraguay  ...        27069
5                 Paraguay  ...        35549
...                    ...  ...          ...
2286  República Dominicana  ...       107476
2287                 Chile  ...      3362.24
2289             Argentina  ...          347
2290  República Dominicana  ...      98749.7
2292                 Chile  ...      1642.27

[1896 rows x 5 columns]

In [33]:
df_ss_19_20_final[['Ocupados2019', 'Ocupados2020']] = df_ss_19_20_final[['Ocupados2019', 'Ocupados2020']].astype(float)

ValueError: ignored

Procedimiento

In [105]:
df_ss_19_20_final.dtypes

País            object
Ciudad          object
Sector          object
Ocupados2019    object
Ocupados2020    object
dtype: object

In [26]:
df_ss_19_20_final['Crecimiento'] = [(df_ss_19_20_final['Ocupados2020'] / df_ss_19_20_final['Ocupados2019'])-1]*100

TypeError: ignored

In [84]:
def zero_exception():
  try:
    growth = [((13/10)-1)]*100
    print(growth)
  except ZeroDivisionError:
    print("Error: división por cero")

In [85]:
zero_exception()

[0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004, 0.30000000000000004]

In [78]:
def growth2020():
  if df_ss_19_20['Ocupados2019'] !=0:
    growth2020 = df_ss_19_20['Ocupados2020'] / df_ss_19_20['Ocupados2019']
    print(growth2020)
  else:
    print("error")

In [79]:
growth2020()

ValueError: ignored

In [22]:
df_ss_19_20['Ocupados2019'].value_counts()

0.000000e+00    26
1.981149e+04     9
4.513946e+04     9
5.105925e+04     9
1.836798e+04     9
                ..
1.332509e+09     1
5.079108e+09     1
1.039820e+05     1
6.634000e+03     1
1.838000e+03     1
Name: Ocupados2019, Length: 1941, dtype: int64

In [61]:
def crecimiento():
  try:
    growth = [(df_ss_19_20['Ocupados2020']/df_ss_19_20['Ocupados2019'])-1]*100
  except: ZeroDivisionError
    growth = 0 if df_ss_19_20['Ocupados2019'] == 0
  print(growth)

IndentationError: ignored

In [47]:
try:
  growth = (((df_ss_19_20['Ocupados2020']/df_ss_19_20['Ocupados2019'])-1)*100)
 
except ZeroDivisionError : 
  growth = 0

In [48]:
growth

0

In [49]:
df_ss_19_20['growth'] = growth
df_ss_19_20

                     País   ... growth
0                 Colombia  ...      0
1                  Ecuador  ...      0
2              El Salvador  ...      0
3                 Paraguay  ...      0
4                    Chile  ...      0
...                    ...  ...    ...
2288                Panamá  ...      0
2289             Argentina  ...      0
2290  República Dominicana  ...      0
2291               Ecuador  ...      0
2292                 Chile  ...      0

[2293 rows x 6 columns]

In [25]:
df_growth

0

In [ ]:
#a: ocupados_2019_sector_ciudad
#c: ocupados_2019_pais
#e: ocupados_2019_sector_pais
a = df2019.groupby(['País ', 'Ciudad', 'Sector', 'Ocupados'], as_index=False).sum()
c = df2019.groupby(['País ', 'Ocupados'], as_index=False).sum()
e = df2019.groupby(['País ', 'Sector', 'Ocupados'], as_index=False).sum()

#b: ocupados_2020_pais
#d: ocupados_2020_sector_pais
#f: ocupados_2020_sector_ciudad
b = df2020.groupby(['País ', 'Ocupados'], as_index=False).sum()
d = df2020.groupby(['País ', 'Sector', 'Ocupados'], as_index=False).sum()
f = df2020.groupby(['País ', 'Ciudad', 'Sector', 'Ocupados'], as_index=False).sum()

#g: NS = a*((b/c)-1)
#h: IM = a*((d/e)-(b/c))
#i: RS = a*((f/a)-(d/e))

In [ ]:
#alternativa 1 de función
def shift_share(a, b, c, d, e, f):
  for i in df_pre_shift_share:
    NS = a*((b/c)-1)
    IM = a*((d/e)-(b/c))
    RS = a*((f/a)-(d/e))
  return(NS, IM, RS)
  print(NS, IM, RS)

In [ ]:
Return(NS)

In [ ]:
#alternativa 2 de función
def NS(a, b, c):
  for i in df_pre_shift_share['pais']
    a = df_pre_shift_share['Año']==2019
    b = df_pre_shift_share['Año']==2020
  for i in df_pre_shift_share['ciudad']
    c =

SyntaxError: ignored

Recomendaciones Daniel: <br> primero hacer manualmente en excel y replicar de manera conjunta para validar resultado de python. <br> merge o joint con las columnas en común de los 2 DF 2019 Vs 2020. Agrupar todos los sectores y observaciones para no tener duplicados: año, ciudad y sector. <br> DF2019+Columnas de 2020. A partir de ese nuevo DF.                        <br> <br>ejemplo:
     df_data = df_data.merge(df_ciudades_sub, how="left", left_on=["Pais ", 'Año', 'Ciudad'], right_on=["-"Pais ", 'Año', 'Ciudad'las columnas del 2020-"]). suffixes=('_x', '_y'): '_2019' '_2020'

In [ ]:
#alternativa 3 de función
def national_share():
  for i in df_pre_shift_share['País ']
    NS = a*((b/c)-1)
  return(NS)

def industry_mix():
  for i in df_pre_shift_share['Sector']
   IM = a*((d/e)-(b/c))
  return(IM)

def regional_share():
  for i in df_pre_shift_share['Ciudad']
  RS = a*((f/a)-(d/e))
  return(RS)

SyntaxError: ignored

In [ ]:
#a: ocupados_2019_sector_ciudad
a = []
  for i in df2019['País']:
    df2019.groupby('Ocupados').sum()
    print(a)
    
#c: ocupados_2019_pais
c = df2019['Ocupados']
#e: ocupados_2019_sector_pais

#b: ocupados_2020_pais
#d: ocupados_2020_sector_pais
#f: ocupados_2020_sector_ciudad

In [ ]:
#a: ocupados_t-1_sector_ciudad
#b: ocupados_t_pais
#c: ocupados_t-1_pais
#d: ocupados_t_sector_pais
#e: ocupados_t-1_sector_pais
#f: ocupados_t_sector_ciudad

def shift_share(zona, periodo_t, periodo_t_1):
  a = df_pre_shift_share['Ocupados'] ocupados_t-1_sector_ciudad
  b = ocupados_t_pais
  c = ocupados_t-1_pais
  d = ocupados_t_sector_pais
  e = ocupados_t-1_sector_pais
  f = ocupados_t_sector_ciudad NS = 

    IM = 
    RS = 

   #g: NS = a*((b/c)-1)
#h: IM = a*((d/e)-(b/c))
#i: RS = a*((f/a)-(d/e))

  #a: ocupados_t-1_sector_ciudad
  #b: ocupados_t_pais
  #c: ocupados_t-1_pais
    a*((b/c)-1)

In [ ]:
def seleccion_area():
  area_elegida = input:"selecciona una zona para el análisis"
seleccion_area

def select_periodos_analisis():
  df_pre_shift_share
  periodo_t = input:"selecciona un año inicial"
    2017
    2018
    2019
  periodo_t_1 = input: "selecciona un año final"
    2020
    2021
  return 
    print("Usted ha seleccionado " periodo_t "como inicio y " periodo_t_1 "como final para el análisis")
    print("el Data frame resultante de shift_share es" df_shift_share)

select_periodos_analisis()

In [ ]:
#g: NS = a*((b/c)-1)
#h: IM = a*((d/e)-(b/c))
#i: RS = a*((f/a)-(d/e))

#a: ocupados_t-1_sector_ciudad
#b: ocupados_t_pais
#c: ocupados_t-1_pais
#d: ocupados_t_sector_pais
#e: ocupados_t-1_sector_pais
#f: ocupados_t_sector_ciudad

NS = []
for i in range(len(df_pre_shift_share)):
  NS_valor = df1_consolidados['Ocupados_2019']*((ocupados_2020/ocupados_2019)-1)
  NS.append(NS_valor)
df1_consolidados["National_Share"] = NS
print(df1_consolidados)

In [ ]:
#Paso 1: DataFrame_filtrado_2019_2020
df_pre_shift_share = df_pre_shift_share.drop(df_pre_shift_share[df_pre_shift_share['Año']<2019].index)
df_pre_shift_share = df_pre_shift_share.drop(df_pre_shift_share[df_pre_shift_share['Año']>2020].index)
df_pre_shift_share

In [ ]:
#Paso2: para DataFrame_filtrado_2019 sacar:
#a: ocupados_t-1_sector_ciudad
#c: ocupados_t-1_pais
#e: ocupados_t-1_sector_pais

In [ ]:
df2019 = []
for pais in range(len(df1_consolidados['Año']))

In [ ]:
#Paso3: para DataFrame_filtrado_2020 sacar
#b: ocupados_t_pais
#d: ocupados_t_sector_pais
#f: ocupados_t_sector_ciudad

In [ ]:
#paso4:
#g: NS = a*((b/c)-1)
#h: IM = a*((d/e)-(b/c))
#i: RS = a*((f/a)-(d/e))

#a: ocupados_t-1_sector_ciudad
#b: ocupados_t_pais
#c: ocupados_t-1_pais
#d: ocupados_t_sector_pais
#e: ocupados_t-1_sector_pais
#f: ocupados_t_sector_ciudad

NS = []
for i in range(len(df1_consolidados)):
  NS_valor = df1_consolidados['Ocupados_2019']*((ocupados_2020/ocupados_2019)-1)
  NS.append(NS_valor)
df1_consolidados["National_Share"] = NS
print(df1_consolidados)

1) National Share:

In [ ]:
#alternativa list comprenhensions
element for element in iterable if condition

#a: ocupados_t-1_sector_ciudad
ocupados for ciudad in periodoT_1 if sector
#c: ocupados_t-1_pais
ocupados for pais in periodoT_1
#e: ocupados_t-1_sector_pais
ocupados for pais in periodoT_1 if sector

#b: ocupados_t_pais
ocupados for pais in periodoT
#d: ocupados_t_sector_pais
ocupados for pais in periodoT if sector
#f: ocupados_t_sector_ciudad
ocupados for ciudad in periodoT if sector


ocupados for ciudad in periodoT_1 if sector
ocupados for pais in periodoT_1
ocupados for pais in periodoT_1 if sector
ocupados for pais in periodoT
ocupados for pais in periodoT if sector
ocupados for ciudad in periodoT if sector

In [ ]:
#alternativa dictionary comprenhension
key: value for value in iterable if condition
ocupados for ciudad in periodoT_1 if sector
ocupados for pais in periodoT_1
ocupados for pais in periodoT_1 if sector
ocupados for pais in periodoT
ocupados for pais in periodoT if sector
ocupados for ciudad in periodoT if sector

In [ ]:
#diferencia 2021 - 2017
df_ss_17vs21a = pd.DataFrame(df_ss_17vs21[4]-df_ss_17vs21[0])
df_ss_17vs21a

In [ ]:
df_ss_17vs21b = df_ss_17vs21a.rename(columns={0: "var2021_2017"})
df_ss_17vs21b

In [ ]:
df_ss_17vs21c = pd.DataFrame((df_ss_17vs21[4]/df_ss_17vs21[0])-1)
df_ss_17vs21c = df_ss_17vs21c.rename(columns={0: "growth2017_2021"}) 
df_ss_17vs21c

In [ ]:
#crecimiento 2021 - 2017
df_mx_ns_17vs21b = pd.DataFrame((dfmxnational_share[3]/dfmxnational_share[0])-1)
df_mx_ns_17vs21c = df_mx_ns_17vs21b.rename(columns={0: "growth2017_2021"}) 
df_mx_ns_17vs21c

2) Regional Share

In [ ]:
dfCiudadesArg = dfARG.groupby(['year', 'city', 'activity'], as_index=False)['employs'].sum()
dfCiudadesArg

In [ ]:
df_bs_as = dfCiudadesArg['city']=='BsAs'
bs_as = dfCiudadesArg[df_bs_as]
bs_as.tail(30)

In [ ]:
df_gran_bs_as = dfCiudadesArg['city']=='PartidosdelGBA'
gran_bs_as = dfCiudadesArg[df_gran_bs_as]
gran_bs_as.head(25)

In [ ]:
df_gran_bs_as = dfCiudadesArg['city']=='PartidosdelGBA'
gran_bs_as = dfCiudadesArg[df_gran_bs_as]
gran_bs_as.tail(25)

3) Industry Mix

In [ ]:
dfCiudadesArg = dfARG.groupby(['year', 'activity'], as_index=False)['employs'].sum()
dfCiudadesArg.tail(30)

In [ ]:
dfindustry_mix = dfCiudadesArg.transpose()
dfindustry_mix

#Visualizaciones

In [ ]:
!pip install plotly_express
import plotly_express as px

In [ ]:
px.scatter(data_frame=df1_base, x='anio', y='ocupados', color='pais')

In [ ]:
px.scatter(data_frame=df1_base, x='ocupados', y='anio', color='pais')

In [ ]:
px.scatter(
    data_frame=df1_base,
    x='anio',
    y='pais',
    log_x=True,
    color='sector',
    size='ocupados',
    size_max=50,
    hover_name='sector'
)

In [ ]:
px.parallel_categories(
    data_frame=df1_base,
    dimensions=['anio', 'pais', 'ocupados'],
    color='pais',
    color_continuous_scale=px.colors.sequential.Burgyl
)

In [ ]:
px.scatter(data_frame=dfCiudadesArg, x='year', y='employs', color='city')

In [ ]:
px.scatter(
    data_frame=dfCiudadesArg,
    x='year',
    y='activity',
    log_x=True,
    color='employs',
    size='employs',
    size_max=50,
    hover_name='activity'
)

In [ ]:
px.scatter(
    data_frame=Total_city_sector_Mex_2017_2021,
    x='year',
    y='employs',
    log_x=True,
    color='city',
    size='employs',
    size_max=60,
    hover_name='activity',
    animation_frame='year',
    range_x=[2017, 2021],
    range_y=[10000, 4000000]
)

In [ ]:
px.scatter(
    data_frame=dfCiudadesArg,
    x='year',
    y='employs',
    log_x=True,
    color='city',
    size='employs',
    size_max=60,
    hover_name='activity',
    animation_frame='year',
    range_x=[2017, 2021],
    range_y=[0, 1000000]
)

In [ ]:
x= pd.read_excel('/content/Libro1.xlsx')

In [ ]:
x
x= x.rename(columns={'CDMX':'Sectores'})
x= x.drop(columns={2017,2021, '2017_R', '2021_R'})
x= x.drop([4, 5])

In [ ]:
sns.set(style='white', palette= "Paired")

x.set_index('Sectores').plot(kind='bar', stacked= True, figsize= (10,10)  )

In [ ]:
R= pd.read_excel('/content/libro 2.xlsx')

In [ ]:
R= R.rename(columns={'Argentina':'Sectores'})
R= R.drop(columns={2017,2021, '2017_R', '2021_R'})
#R= R.drop([4, 5])

In [ ]:
sns.set(style='white', palette= "Paired")

R.set_index('Sectores').plot(kind='bar', stacked= True, figsize= (10,10)  )

Notas Generales 24 enero

Datos:<br>
1) Ajustar sectores duplicados: (0 con NSNR y Mal Definidas), (actividades financieras), (servicios) <br>
Alternativas de temporalidad: <br>
a) Primer periodo Vs último periodo <br>
b1) bloque pre covid (promedio 2019 y antes) Vs post covid (promedio 2020 en adelante) <br>
b2) bloque pre covid (promedio 2019 y antes) Vs último dato post 2020

Visualizaciones <br>
1) (todos con todos por Regiones: caribe, sudamérica y centroamérica) aros de ocupaciones por sectores por países <br>
2) (Yo con yo) Araña por país porcentual por sectores con líneas por año <br>
3) (Yo con yo) Araña por sectores porcentual por regiones de países con líneas por año <br>
4) (georreferenciación) mayor impacto 2019 Vs 2020 <br>
5) (georreferenciación) mayor recuperación 2020 Vs 2021 <br>

Notas Generales 25 enero <br>
1) Sacar código gran tabla de SS LATAM <br>
2) Sacar código gráficas PPT